# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2019-07-02 13:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('state_check', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lecture_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='state_check.Lecture')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='state_check.Student')),
            ],
        ),
    ]
