# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2019-07-02 13:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('state_check', '0002_attendance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='lecture_id',
            new_name='lecture',
        ),
        migrations.RenameField(
            model_name='attendance',
            old_name='student_id',
            new_name='student',
        ),
    ]
