# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2019-07-02 13:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('state_check', '0003_auto_20190702_1301'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.RemoveField(
            model_name='student',
            name='group_id',
        ),
        migrations.AddField(
            model_name='lecture',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='state_check.Group'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='state_check.Group'),
            preserve_default=False,
        ),
    ]
