# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2019-07-04 11:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('state_check', '0004_auto_20190702_1310'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='lecture',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='student',
        ),
        migrations.AddField(
            model_name='student',
            name='lectures',
            field=models.ManyToManyField(to='state_check.Lecture'),
        ),
        migrations.AlterField(
            model_name='student',
            name='image_st',
            field=models.ImageField(upload_to='students/'),
        ),
        migrations.DeleteModel(
            name='Attendance',
        ),
    ]
