# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2019-07-12 09:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('state_check', '0007_auto_20190704_1239'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='students/')),
            ],
        ),
        migrations.RemoveField(
            model_name='student',
            name='image_st',
        ),
        migrations.AddField(
            model_name='student',
            name='short_name',
            field=models.SlugField(default='', unique=True),
        ),
        migrations.AddField(
            model_name='studentphoto',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='state_check.Student'),
        ),
    ]
