# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2019-07-12 09:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('state_check', '0008_auto_20190712_0928'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='lectures',
        ),
        migrations.AddField(
            model_name='lecture',
            name='students',
            field=models.ManyToManyField(to='state_check.Student'),
        ),
    ]
