# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2019-07-12 09:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('state_check', '0009_auto_20190712_0931'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lecture',
            old_name='image_aud',
            new_name='photo_aud',
        ),
        migrations.RenameField(
            model_name='studentphoto',
            old_name='image',
            new_name='photo',
        ),
    ]
