# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2019-07-12 10:57
from __future__ import unicode_literals

import any_imagefield.models.fields
from django.db import migrations, models
import django.db.models.deletion
import state_check.models


class Migration(migrations.Migration):

    dependencies = [
        ('state_check', '0010_auto_20190712_0938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentphoto',
            name='photo',
            field=any_imagefield.models.fields.AnyImageField(blank=True, null=True, upload_to=state_check.models.StudentPhoto.get_upload_path),
        ),
        migrations.AlterField(
            model_name='studentphoto',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='state_check.Student'),
        ),
    ]
