# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2019-07-12 12:03
from __future__ import unicode_literals

from django.db import migrations, models
import sorl.thumbnail.fields
import state_check.models


class Migration(migrations.Migration):

    dependencies = [
        ('state_check', '0011_auto_20190712_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='middle_name',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='studentphoto',
            name='photo',
            field=sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to=state_check.models.StudentPhoto.get_upload_path),
        ),
    ]
