# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2019-07-12 12:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('state_check', '0012_auto_20190712_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='middle_name',
            field=models.CharField(blank=True, default=' ', max_length=128),
            preserve_default=False,
        ),
    ]
