# Generated by Django 2.2.3 on 2019-07-14 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('state_check', '0014_auto_20190712_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='students',
            field=models.ManyToManyField(blank=True, to='state_check.Student'),
        ),
    ]
