# Generated by Django 2.2.3 on 2019-07-14 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('state_check', '0016_auto_20190714_1435'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['last_name', 'first_name', 'middle_name']},
        ),
    ]
